In [1]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [11, 12, 13]])

In [2]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
flat = arr.flatten()

In [4]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [5]:
flat[0]

np.int64(1)

In [6]:
flat[3: 6]

array([4, 5, 6])

In [7]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [8]:
flat[3:] # same as flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [9]:
flat[3:13]

array([ 4,  5,  6,  7,  8,  9, 11, 12, 13])

In [10]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [11]:
b = flat[3:7].copy() # This is not a slice because we are using copy method to get the copy

In [12]:
b


array([4, 5, 6, 7])

In [13]:
b[0] = 444444666

In [14]:
arr = np.array([1, 54, 23, 53, 2, 3, 34, 5, 6])

In [15]:
arr[[1, 4, 6]]

array([54,  2, 34])

In [16]:
arr[arr>23]

array([54, 53, 34])

In [17]:
# 1. Create a 3×3 array filled with random numbers and print its shape
arr_random = np.random.rand(3, 3)
print("Random Array:\n", arr_random)
print("Shape:", arr_random.shape)

Random Array:
 [[0.12543026 0.86023095 0.59446672]
 [0.37639599 0.9483994  0.77908981]
 [0.00865869 0.91473145 0.73202787]]
Shape: (3, 3)


In [18]:
# 2. Convert an array of floats [1.1, 2.2, 3.3] into integers
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(int)
print("\nInteger Array:", int_arr)


Integer Array: [1 2 3]


In [19]:
# 3. Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]
arr = np.array([1, 2, 3, 4, 5, 6])
even_numbers = arr[[1, 3, 5]]  # indices of even values
print("\nEven Numbers (Fancy Indexing):", even_numbers)


Even Numbers (Fancy Indexing): [2 4 6]


In [20]:
# 4. Reshape a 1D array of size 9 into a 3×3 matrix
one_d = np.arange(1, 10)
matrix = one_d.reshape(3, 3)
print("\n3x3 Matrix:\n", matrix)


3x3 Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [21]:
# 5. Use boolean masking to filter numbers greater than 50 in an array
numbers = np.array([10, 55, 23, 78, 49, 90, 12])
filtered = numbers[numbers > 50]
print("\nNumbers > 50:", filtered)


Numbers > 50: [55 78 90]
